# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d5f8ba966d53666f87133b5d2a9b66ce"
name = "zd-243434"
handle = "zd-243434"
application_url = "https://renaissance-tampa-polished-templates.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-a62d38fd.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://renaissance-tampa-polished-templates.trycloudflare.com/auth/callback",
  "https://renaissance-tampa-polished-templates.trycloudflare.com/auth/shopify/callback",
  "https://renaissance-tampa-polished-templates.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
